
const SETV=()=>{try{return JSON.parse(localStorage.getItem('restock-settings'))||{}}catch(e){return{}}};const KEY='restock_v2',TODAY='2026-09-30',$=s=>document.querySelector(s)||document.createElement('div'),inr=n=>(SETV().cur||'₹')+Math.round(n).toLocaleString('en-IN');
const P={dash:'<rect x="3" y="3" width="7" height="9" rx="1"/><rect x="14" y="3" width="7" height="5" rx="1"/><rect x="14" y="12" width="7" height="9" rx="1"/><rect x="3" y="16" width="7" height="5" rx="1"/>',box:'<path d="M21 8l-9-5-9 5v8l9 5 9-5z"/><path d="M3 8l9 5 9-5M12 13v8"/>',boxes:'<path d="M7 10l-4 2v6l4 2 4-2v-6zM3 12l4 2 4-2M7 14v6M17 4l-4 2v6l4 2 4-2V6zM13 6l4 2 4-2M17 8v6"/>',cart:'<path d="M3 3h2l2.5 12h11L21 7H6"/><circle cx="9" cy="20" r="1"/><circle cx="18" cy="20" r="1"/>',truck:'<path d="M2 6h11v10H2zM13 9h4l4 4v3h-8"/><circle cx="6" cy="18" r="1.5"/><circle cx="17" cy="18" r="1.5"/>',bell:'<path d="M6 8a6 6 0 0112 0c0 7 3 8 3 8H3s3-1 3-8M10 20a2 2 0 004 0"/>',chart:'<path d="M3 3v18h18M7 15l4-5 3 3 5-7"/>',users:'<circle cx="9" cy="8" r="3.5"/><path d="M2 20c0-4 3-6 7-6s7 2 7 6M17 4a3.5 3.5 0 010 7M22 20c0-3-2-5-4-5.5"/>',hist:'<path d="M3 12a9 9 0 109-9 9 9 0 00-7 3.5M3 4v4h4M12 7v5l3 2"/>',ref:'<path d="M21 12a9 9 0 01-15.5 6.2M3 12A9 9 0 0118.5 5.8M21 4v4h-4M3 20v-4h4"/>',spark:'<path d="M12 3l1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8zM19 16l.8 2.2L22 19l-2.2.8L19 22l-.8-2.2L16 19l2.2-.8z"/>',gear:'<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1L7 17M17 7l2.1-2.1"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.5 2.5 0 015 .5c0 1.8-2.5 2-2.5 3.5M12 17h.01"/>',search:'<circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/>',warn:'<path d="M12 3l10 18H2zM12 10v5M12 18h.01"/>',alert:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6M12 16h.01"/>',plus:'<path d="M12 5v14M5 12h14"/>',menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',x:'<path d="M6 6l12 12M18 6L6 18"/>',cal:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M3 10h18M8 3v4M16 3v4"/>',chev:'<path d="M6 9l6 6 6-6"/>',adj:'<path d="M4 6h10M18 6h2M4 12h4M12 12h8M4 18h12"/><circle cx="16" cy="6" r="2"/><circle cx="10" cy="12" r="2"/><circle cx="18" cy="18" r="2"/>'};
const ic=n=>`<svg class="i" viewBox="0 0 24 24" aria-hidden="true">${P[n]}</svg>`;
const seed=()=>{const now=Date.now(),m=60e3,pr=[['Maggi 70g','Food','MG70',8,10,4,'Nestle Distributor',11,14],['Coca-Cola 750ml','Beverages','CC750',6,12,5,'Local Beverages Supplier',32,40],['Aashirvaad Atta 5kg','Groceries','AA5',0,8,3,'ITC Distributor',235,265],['Parle-G Biscuits','Snacks','PG100',7,10,2,'Parle Distributor',8,10],['Tata Salt 1kg','Groceries','TS1',15,10,1,'Tata Distributor',22,28],['Amul Milk 1L','Beverages','BV-AML-1L',34,20,6,'Amul Dairy Depot',60,68],['Lays Classic 52g','Snacks','SN-LAY-052',22,12,3,'PepsiCo Distributor',16,20],['Dettol Soap 75g','Personal Care','PC-DET-075',41,15,1,'HUL Distributor',34,42],['Crocin Advance','Pharmacy','PH-CRO-015',28,10,2,'City Pharma Wholesale',18,24],['Surf Excel 1kg','Household','HH-SRF-1K',19,8,1,'HUL Distributor',105,125]].map((a,i)=>({id:i+1,name:a[0],category:a[1],sku:a[2],stock:a[3],reorderLevel:a[4],dailySales:a[5],supplier:a[6],purchasePrice:a[7],sellingPrice:a[8]}));
return{products:pr,sales:[{id:1,product:'Maggi 70g',quantity:4,price:14,date:'2026-09-30',seed:1},{id:2,product:'Coca-Cola 750ml',quantity:3,price:40,date:'2026-09-30',seed:1},{id:3,product:'Amul Milk 1L',quantity:6,price:68,date:'2026-09-30',seed:1},{id:4,product:'Parle-G Biscuits',quantity:5,price:10,date:'2026-09-30',seed:1},{id:5,product:'Lays Classic 52g',quantity:4,price:20,date:'2026-09-30',seed:1},{id:6,product:'Crocin Advance',quantity:2,price:24,date:'2026-09-30',seed:1},{id:7,product:'Dettol Soap 75g',quantity:2,price:42,date:'2026-09-30',seed:1},{id:8,product:'Surf Excel 1kg',quantity:1,price:125,date:'2026-09-30',seed:1}],purchases:[{id:1,product:'Tata Salt 1kg',supplier:'Tata Distributor',quantity:10,price:22,date:'2026-09-30',seed:1},{id:2,product:'Amul Milk 1L',supplier:'Amul Dairy Depot',quantity:40,price:60,date:'2026-09-30',seed:1},{id:3,product:'Dettol Soap 75g',supplier:'HUL Distributor',quantity:24,price:34,date:'2026-09-30',seed:1},{id:4,product:'Crocin Advance',supplier:'City Pharma Wholesale',quantity:30,price:18,date:'2026-09-30',seed:1},{id:5,product:'Lays Classic 52g',supplier:'PepsiCo Distributor',quantity:36,price:16,date:'2026-09-30',seed:1},{id:6,product:'Surf Excel 1kg',supplier:'HUL Distributor',quantity:12,price:105,date:'2026-09-30',seed:1}],reorders:[{id:1,product:'Maggi 70g',supplier:'Nestle Distributor',quantity:20,status:'Pending',date:'2026-09-30'},{id:2,product:'Coca-Cola 750ml',supplier:'Local Beverages Supplier',quantity:24,status:'Ordered',date:'2026-09-29'},{id:3,product:'Aashirvaad Atta 5kg',supplier:'ITC Distributor',quantity:16,status:'Pending',date:'2026-09-30'},{id:4,product:'Parle-G Biscuits',supplier:'Parle Distributor',quantity:30,status:'Pending',date:'2026-09-28'}],
activity:[{t:'sale',x:'Maggi 70g × 4',ts:now-2*m},{t:'purchase',x:'Tata Salt 1kg × 20',ts:now-18*m},{t:'alert',x:'Coca-Cola 750ml reached reorder level',ts:now-32*m},{t:'add',x:'Parle-G Biscuits',ts:now-60*m}],
extra:{products:118,stock:2306,low:9,out:3,rq:{Pending:5,Ordered:4,Received:12}},base:{'Maggi 70g':96,'Coca-Cola 750ml':84,'Parle-G Biscuits':71,'Amul Milk 1L':63,'Tata Salt 1kg':44},mv:{in:410,out:372},suppliers:[{id:1,name:'Nestle Distributor',category:'Food',products:24,orders:3,status:'Active',contact:'orders@nestle-dist.demo'},{id:2,name:'ITC Distributor',category:'Groceries',products:18,orders:2,status:'Active',contact:'sales@itc-dist.demo'},{id:3,name:'Local Beverages Supplier',category:'Beverages',products:14,orders:1,status:'Active',contact:'hello@localbev.demo'},{id:4,name:'Parle Distributor',category:'Snacks',products:11,orders:1,status:'Active',contact:'orders@parle-dist.demo'},{id:5,name:'Tata Distributor',category:'Groceries',products:9,orders:0,status:'Active',contact:'trade@tata-dist.demo'},{id:6,name:'Amul Dairy Depot',category:'Beverages',products:7,orders:0,status:'Active',contact:'depot@amul-dairy.demo'},{id:7,name:'PepsiCo Distributor',category:'Snacks',products:8,orders:0,status:'Inactive',contact:'sales@pepsi-dist.demo'},{id:8,name:'HUL Distributor',category:'Household',products:16,orders:0,status:'Active',contact:'orders@hul-dist.demo'},{id:9,name:'City Pharma Wholesale',category:'Pharmacy',products:12,orders:0,status:'Active',contact:'care@citypharma.demo'}],hist:[{d:'2026-09-30',p:'Maggi 70g',t:'Sale',q:-4,prev:12,now:8,ref:'SALE-1042'},{d:'2026-09-30',p:'Tata Salt 1kg',t:'Purchase',q:10,prev:5,now:15,ref:'PUR-0318'},{d:'2026-09-30',p:'Coca-Cola 750ml',t:'Sale',q:-3,prev:9,now:6,ref:'SALE-1041'},{d:'2026-09-30',p:'Aashirvaad Atta 5kg',t:'Sale',q:-3,prev:3,now:0,ref:'SALE-1039'},{d:'2026-09-30',p:'Amul Milk 1L',t:'Stock Received',q:40,prev:0,now:40,ref:'REO-0207'}]}};
let S;try{S=JSON.parse(localStorage.getItem(KEY))}catch(e){}if(!S||!S.products)S=seed();
const HT={sale:'Sale',purchase:'Purchase',adjust:'Adjustment',add:'Adjustment'};let hint=null;
const save=()=>{S.snap=S.snap||{};S.products.forEach(p=>{const o=S.snap[p.id];if(o!==undefined&&o!==p.stock){const a=S.activity[0];S.hist.unshift({d:TODAY,p:p.name,t:hint||(a&&Date.now()-a.ts<2500&&HT[a.t])||'Adjustment',q:p.stock-o,prev:o,now:p.stock,ref:'REF-'+(1043+S.hist.length)})}S.snap[p.id]=p.stock});S.hist=S.hist.slice(0,200);hint=null;try{localStorage.setItem(KEY,JSON.stringify(S))}catch(e){}};
const stat=p=>p.stock===0?'out':p.stock<=p.reorderLevel?'low':'ok',LBL={ok:'Healthy',low:'Low Stock',out:'Out of Stock'};
const open=p=>S.reorders.some(r=>r.product===p.name&&r.status!=='Received');
const cnt=()=>{const L=S.products.filter(p=>stat(p)==='low').length+S.extra.low,O=S.products.filter(p=>stat(p)==='out').length+S.extra.out,T=S.products.length+S.extra.products;return{T,L,O,H:T-L-O,U:S.products.reduce((a,p)=>a+p.stock,0)+S.extra.stock}};
const ago=t=>{const m=Math.floor((Date.now()-t)/6e4);return m<1?'Just now':m<60?m+' minutes ago':m<120?'1 hour ago':Math.floor(m/60)+' hours ago'};
const log=(t,x)=>{S.activity.unshift({t,x,ts:Date.now()});S.activity=S.activity.slice(0,30)};
function toast(m,er){const t=document.createElement('div');t.className='toast'+(er?' er':'');t.innerHTML=`<span class="${er?'c-r':'c-g'}">${ic(er?'alert':'spark')}</span>${m}`;$('#toasts').append(t);setTimeout(()=>t.classList.add('x'),3600);setTimeout(()=>t.remove(),4100)}
function changed(p,prev){const n=stat(p);if(n!==prev&&n!=='ok')log('alert',n==='out'?p.name+' is out of stock':p.name+' reached reorder level')}
/* ---- render ---- */
let range=7,query='';
function renderKpis(){const c=cnt();const k=[['Total Products',c.T,'+8 this month','box','↑ 8 new','c-c'],['Total Stock',c.U.toLocaleString('en-IN'),'Units currently available','boxes','Live count','c-g'],['Low Stock',c.L,'Products need attention','warn','Review soon','c-a'],['Out of Stock',c.O,'Products unavailable','alert','Act now','c-r']];
$('#kpis').innerHTML=k.map(a=>`<div class="card kpi"><div class="top"><span>${a[0]}</span><span class="ico ${a[5]}">${ic(a[3])}</span></div><div class="n">${a[1]}</div><div class="sub">${a[2]}</div><span class="chip ${a[5]}">${a[4]}</span></div>`).join('');
const n=[c.L,c.O,S.reorders.filter(r=>r.status==='Pending').length].filter(x=>x>0).length;$('#badge').textContent=n;$('#badge').style.display=n?'grid':'none'}
const WK=[8400,9200,7850,10100,11300,12450,9800],DN=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
function series(){const ex=S.sales.filter(s=>!s.seed).reduce((a,s)=>a+s.quantity*s.price,0);let v,l;
if(range==7){v=[...WK];v[2]+=ex;l=DN}else if(range==30){v=Array.from({length:30},(_,i)=>Math.round(8200+(Math.sin(i*1.7)+Math.sin(i*.6))*1400+(i%7>3?1300:0)));v[29]+=ex;l=v.map((_,i)=>'Sep '+(i+1))}else{v=Array.from({length:13},(_,i)=>Math.round(56000+Math.sin(i*1.3)*6000+i*450));v[12]+=ex;l=v.map((_,i)=>'Wk '+(i+1))}
return v.map((x,i)=>({v:x,l:l[i]}))}
function renderChart(){const d=series(),tot=d.reduce((a,x)=>a+x.v,0),tx=range==7?186+S.sales.filter(s=>!s.seed).length:Math.round(tot/366);
$('#sstats').innerHTML=`<div><span>Total Sales</span><b>${inr(tot)}</b></div><div><span>Transactions</span><b>${tx}</b></div><div><span>Average Order</span><b>${inr(tot/tx)}</b></div>`;
const W=640,H=250,pl=44,pb=28,pt=14,pr=10,mx=Math.ceil(Math.max(...d.map(x=>x.v))/2000)*2000,bw=(W-pl-pr)/d.length,X=i=>pl+bw*i+bw/2,Y=v=>pt+(H-pt-pb)*(1-v/mx),w=Math.min(bw*.55,30),st=Math.ceil(d.length/7);let g='';
for(let i=0;i<=4;i++){const y=pt+(H-pt-pb)*i/4;g+=`<line x1="${pl}" x2="${W-pr}" y1="${y}" y2="${y}" class="gl"/><text x="${pl-8}" y="${y+4}" text-anchor="end" class="ax">₹${Math.round(mx*(1-i/4)/1000)}k</text>`}
let path='M'+X(0)+','+Y(d[0].v);for(let i=1;i<d.length;i++){const a=X(i-1),b=X(i),m=(a+b)/2;path+=`C${m},${Y(d[i-1].v)} ${m},${Y(d[i].v)} ${b},${Y(d[i].v)}`}
$('#cw').innerHTML=`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Sales chart">${g}${d.map((p,i)=>`<rect class="bar" data-b="${i}" x="${X(i)-w/2}" y="${Y(p.v)}" width="${w}" height="${H-pb-Y(p.v)}" rx="4" style="animation-delay:${i*25}ms"/>${i%st==0?`<text x="${X(i)}" y="${H-8}" text-anchor="middle" class="ax">${p.l}</text>`:''}`).join('')}<path class="ln" pathLength="1" d="${path}"/>${d.map((p,i)=>`<circle cx="${X(i)}" cy="${Y(p.v)}" r="${d.length>14?0:3.5}" fill="var(--card)" stroke="#5fd0c8" stroke-width="2"/>`).join('')}${d.map((p,i)=>`<rect data-i="${i}" x="${pl+bw*i}" y="0" width="${bw}" height="${H-pb}" fill="transparent"/>`).join('')}</svg><div class="tip" id="tip"></div>`;
const svg=$('#cw svg'),tip=$('#tip');svg.querySelectorAll('[data-i]').forEach(r=>{const i=+r.dataset.i;r.onmouseenter=r.onfocus=()=>{const k=svg.clientWidth/W;tip.style.left=X(i)*k+'px';tip.style.top=Y(d[i].v)*k+'px';tip.innerHTML=`<b>${d[i].l}</b> · ${inr(d[i].v)}`;tip.style.opacity=1;svg.querySelector(`[data-b="${i}"]`).classList.add('h')};r.onmouseleave=()=>{tip.style.opacity=0;svg.querySelectorAll('.bar.h').forEach(b=>b.classList.remove('h'))}})}
function renderHealth(){const c=cnt(),pc=[c.H,c.L,c.O].map(x=>Math.round(x/c.T*100)),col=['#5ccb8a','#e3b04b','#ee6d6d'],R=64,C=2*Math.PI*R;let off=0;
const seg=[c.H,c.L,c.O].map((x,i)=>{const len=x/c.T*C,s=`<circle r="${R}" cx="90" cy="90" fill="none" stroke="${col[i]}" stroke-width="16" stroke-dasharray="${Math.max(len-2,0)} ${C}" stroke-dashoffset="${-off}" transform="rotate(-90 90 90)" opacity=".85"/>`;off+=len;return s}).join('');
$('#health').innerHTML=`<div class="donutw"><svg viewBox="0 0 180 180" role="img" aria-label="Inventory health donut"><circle r="${R}" cx="90" cy="90" fill="none" stroke="#20252b" stroke-width="16"/>${seg}</svg><div class="dc"><b>${pc[0]}%</b><span>Healthy</span></div></div>
<div class="leg"><div><i style="background:${col[0]}"></i>Healthy Stock (${pc[0]}%)<span>${c.H} products</span></div><div><i style="background:${col[1]}"></i>Low Stock (${pc[1]}%)<span>Needs Attention: ${c.L}</span></div><div><i style="background:${col[2]}"></i>Out of Stock (${pc[2]}%)<span>Unavailable: ${c.O}</span></div></div>`}
function renderTable(){const q=query.trim().toLowerCase(),o={out:0,low:1,ok:2};let l=[...S.products].sort((a,b)=>o[stat(a)]-o[stat(b)]);
if(q)l=l.filter(p=>[p.name,p.category,p.sku,p.supplier].some(x=>x.toLowerCase().includes(q)));else l=l.filter(p=>stat(p)!=='ok'||['Tata Salt 1kg'].includes(p.name));
$('#tb').innerHTML=l.map(p=>`<tr><td><b>${p.name}</b><small>${p.sku}</small></td><td>${p.category}</td><td><b>${p.stock}</b></td><td>${p.reorderLevel}</td><td>${p.dailySales}/day</td><td><span class="b ${stat(p)}">${LBL[stat(p)]}</span>${open(p)?'<span class="b rq">Reorder Requested</span>':''}</td><td><button class="btn" data-v="${p.id}">View</button> <button class="btn" data-o="${p.id}" ${open(p)?'disabled':''}>Reorder</button></td></tr>`).join('');
const e=$('#tbe');if(!S.products.length)e.innerHTML='<div class="empty"><b>No products yet</b>Add your first product to start tracking inventory.<br><button class="btn p" data-act="add">Add Product</button></div>';
else if(!l.length&&q)e.innerHTML='<div class="empty"><b>No products found</b>Nothing matches “'+q.replace(/</g,'&lt;')+'”. Try a different name, SKU or category.</div>';
else if(!l.length)e.innerHTML='<div class="empty"><b>No alerts</b>All products are above their reorder levels.</div>';else e.innerHTML=''}
const AI={sale:['cart','Sale recorded','c-g'],purchase:['truck','Purchase received','c-c'],alert:['warn','Low stock alert','c-a'],add:['box','Product added','c-c'],adjust:['adj','Stock adjusted','c-c'],reorder:['ref','Reorder created','c-c']};
function renderAct(){$('#act').innerHTML=S.activity.length?S.activity.slice(0,7).map(a=>{const m=AI[a.t];return`<li><span class="ico ${m[2]}">${ic(m[0])}</span><div><b>${m[1]}</b><small>${a.x}</small></div><span class="t">${ago(a.ts)}</span></li>`}).join(''):'<div class="empty"><b>No recent activity</b>Record a sale or purchase to see it here.</div>'}
function renderAI(){const c=S.products.filter(p=>p.stock>0&&p.dailySales>0).map(p=>({p,d:p.stock/p.dailySales})).sort((a,b)=>a.d-b.d)[0];let h=`<div class="ch"><div><h3>AI Inventory Insight</h3></div><span class="tag">Demo AI Insight</span></div>`;
if(c&&c.d<=7){const p=c.p;h+=`<h4>${p.name} may need replenishment soon.</h4><div class="mini"><div><span>Current Stock</span><b>${p.stock} units</b></div><div><span>Avg Daily Sales</span><b>${p.dailySales}/day</b></div><div><span>Stock Remaining</span><b>~${Math.max(1,Math.round(c.d))} days</b></div></div><p class="sub" style="margin-bottom:12px">Suggested action: Consider reordering soon.</p><button class="btn p" data-o="${p.id}" ${open(p)?'disabled':''}>${open(p)?'Reorder Requested':'Create Reorder'}</button>`}
else h+='<h4>Stock levels look stable.</h4><p class="sub">No product is projected to run out within a week.</p>';
$('#sec-ai').innerHTML=h+'<p class="note">Example recommendation based on demo sales and inventory data.</p>'}
function renderTop(){const u={};Object.entries(S.base).forEach(([k,v])=>u[k]=v);S.sales.filter(s=>!s.seed).forEach(s=>u[s.product]=(u[s.product]||0)+s.quantity);const l=Object.entries(u).sort((a,b)=>b[1]-a[1]).slice(0,5),m=l[0][1];
$('#top').innerHTML=l.map(([n,v])=>`<div><div class="r"><span>${n}</span><b>${v} <small class="sub">units</small></b></div><div class="trk"><i data-w="${v/m*100}"></i></div></div>`).join('');requestAnimationFrame(()=>document.querySelectorAll('#top i').forEach(i=>i.style.width=i.dataset.w+'%'))}
function renderMove(){const a=S.mv.in,b=S.mv.out,m=Math.max(a,b),n=a-b;$('#mv').innerHTML=`<div class="fl" style="grid-template-columns:repeat(3,1fr);display:grid;gap:10px"><div><span class="sub">Stock In</span><div class="big c-g">${a}</div></div><div><span class="sub">Stock Out</span><div class="big c-a">${b}</div></div><div><span class="sub">Net Movement</span><div class="big">${n>=0?'+':''}${n}</div></div></div>
<div><div class="r" style="display:flex;justify-content:space-between"><span class="sub">In</span></div><div class="trk"><i style="width:${a/m*100}%;background:var(--gr)"></i></div></div><div><div class="trk"><i style="width:${b/m*100}%;background:var(--am)"></i></div><span class="sub" style="font-size:12px">Out</span></div>`}
function renderReorders(){$('#rb').innerHTML=S.reorders.map(r=>`<tr><td><b>${r.product}</b></td><td>${r.supplier}</td><td>${r.quantity}</td><td><select class="st" data-r="${r.id}" aria-label="Status for ${r.product}">${['Pending','Ordered','Received'].map(s=>`<option ${s==r.status?'selected':''}>${s}</option>`).join('')}</select></td><td>${new Date(r.date+'T00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</td></tr>`).join('');
$('#rbe').innerHTML=S.reorders.length?'':'<div class="empty"><b>No reorder requests</b>Reorder a low-stock product to create your first request.</div>'}
function renderBase(){renderKpis();renderChart();renderHealth();renderTable();renderAct();renderAI();renderTop();renderMove();renderReorders();save()}
/* ---- modal ---- */
let lastF;const ov=$('#ov'),md=$('#md');
const fld=(l,id,t='text',x='',w='')=>`<div class="fl ${w}"><label for="${id}">${l}</label><input id="${id}" type="${t}" ${x}></div>`,
sel=(l,id,o,w='')=>`<div class="fl ${w}"><label for="${id}">${l}</label><select id="${id}">${o}</select></div>`,
popt=()=>S.products.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');
function modal(title,body,label,fn,after){lastF=document.activeElement;md.innerHTML=`<h3 id="mt">${title}<button class="ib" type="button" data-close aria-label="Close">${ic('x')}</button></h3><form id="mf" novalidate>${body}<div class="acts"><button type="button" class="btn" data-close>${label?'Cancel':'Close'}</button>${label?`<button class="btn p" type="submit">${label}</button>`:''}</div></form>`;
ov.classList.add('open');$('#mf').onsubmit=e=>{e.preventDefault();if(!$('#mf').checkValidity()){$('#mf').reportValidity();return}if(fn(v=>$('#'+v).value)!==false)closeM()};after&&after();setTimeout(()=>{const f=md.querySelector('input,select');f&&f.focus()},60)}
function closeM(){ov.classList.remove('open');lastF&&lastF.focus&&lastF.focus()}
ov.onclick=e=>{if(e.target===ov||e.target.closest('[data-close]'))closeM()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeM();$('#dd').classList.remove('open');$('#side').classList.remove('open');$('#veil').classList.remove('open')}
if(e.key==='Tab'&&ov.classList.contains('open')){const f=[...md.querySelectorAll('button,input,select')].filter(x=>!x.disabled);if(!f.length)return;const a=f[0],b=f[f.length-1];if(e.shiftKey&&document.activeElement===a){e.preventDefault();b.focus()}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a.focus()}}});
const byId=id=>S.products.find(p=>p.id==id),CATS=['Food','Beverages','Groceries','Snacks','Personal Care','Pharmacy','Household'].map(c=>`<option>${c}</option>`).join('');
function mAdd(){modal('Add Product',`<div class="fr">${fld('Product Name','f1','text','required','w')}${fld('SKU','f2','text','required')}${sel('Category','f3',CATS)}${fld('Opening Stock','f4','number','required min="0" value="0"')}${fld('Reorder Level','f5','number','required min="0" value="10"')}${fld('Supplier','f6','text','required','w')}${fld('Purchase Price (₹)','f7','number','required min="0" step="0.01"')}${fld('Selling Price (₹)','f8','number','required min="0" step="0.01"')}</div>`,'Add Product',g=>{const p={id:Date.now(),name:g('f1').trim(),sku:g('f2').trim(),category:g('f3'),stock:+g('f4'),reorderLevel:+g('f5'),dailySales:0,supplier:g('f6').trim(),purchasePrice:+g('f7'),sellingPrice:+g('f8')};S.products.push(p);log('add',p.name);changed(p,'ok');renderAll();toast('Product added successfully')})}
function mSale(id){modal('Record Sale',`<div class="fr">${sel('Product','f1',popt(),'w')}${fld('Quantity','f2','number','required min="1" value="1"')}${fld('Selling Price (₹)','f3','number','required min="0" step="0.01"')}${fld('Date','f4','date','required value="'+TODAY+'"','w')}</div><div class="info"><div><span>Current Stock</span><b id="cs"></b></div><div><span>Remaining Stock</span><b id="rs"></b></div><div><span>Total Amount</span><b id="ta"></b></div></div>`,'Record Sale',g=>{const p=byId(g('f1')),q=+g('f2');if(q>p.stock){toast(`Only ${p.stock} units of ${p.name} in stock`,1);return false}const pv=stat(p);p.stock-=q;S.sales.push({id:Date.now(),product:p.name,quantity:q,price:+g('f3'),date:g('f4')});S.mv.out+=q;log('sale',`${p.name} × ${q}`);changed(p,pv);renderAll();toast('Sale recorded successfully')},()=>{const s=$('#f1'),u=()=>{const p=byId(s.value);if(p){$('#f3').value=p.sellingPrice;$('#cs').textContent=p.stock+' units'}};const t=()=>{const p=byId(s.value),q=+$('#f2').value||0;$('#rs').textContent=p?Math.max(0,p.stock-q)+' units':'';$('#ta').textContent=inr(q*(+$('#f3').value||0))};['f2','f3'].forEach(k=>$('#'+k).oninput=t);s.onchange=()=>{u();t()};if(id)s.value=id;u();t()})}
function mPur(id){modal('Record Purchase',`<div class="fr">${sel('Product','f1',popt(),'w')}${fld('Supplier','f2','text','required','w')}${fld('Quantity','f3','number','required min="1" value="10"')}${fld('Purchase Price (₹)','f4','number','required min="0" step="0.01"')}${fld('Date','f5','date','required value="'+TODAY+'"','w')}</div>`,'Record Purchase',g=>{const p=byId(g('f1')),q=+g('f3');p.stock+=q;p.supplier=g('f2').trim();S.purchases.push({id:Date.now(),product:p.name,supplier:p.supplier,quantity:q,price:+g('f4'),date:g('f5')});S.mv.in+=q;log('purchase',`${p.name} × ${q}`);renderAll();toast('Purchase recorded successfully')},()=>{const s=$('#f1'),u=()=>{const p=byId(s.value);if(p){$('#f2').value=p.supplier;$('#f4').value=p.purchasePrice}};s.onchange=u;u()})}
function mAdj(){modal('Stock Adjustment',`<div class="fr">${sel('Product','f1',popt(),'w')}${sel('Adjustment','f2','<option value="set">Set exact count</option><option value="add">Add units</option><option value="rem">Remove units</option>')}${fld('Quantity','f3','number','required min="0" value="0"')}${sel('Reason','f4','<option>Stock count correction</option><option>Damaged goods</option><option>Expired</option><option>Returned</option>','w')}</div><div class="info"><div><span>Current Stock</span><b id="cs"></b></div></div>`,'Save Adjustment',g=>{const p=byId(g('f1')),q=+g('f3'),m=g('f2'),pv=stat(p),o=p.stock;p.stock=m==='set'?q:m==='add'?o+q:Math.max(0,o-q);if(m==='add')S.mv.in+=q;if(m==='rem')S.mv.out+=Math.min(q,o);log('adjust',`${p.name}: ${o} → ${p.stock} (${g('f4')})`);changed(p,pv);renderAll();toast('Stock updated successfully')},()=>{const s=$('#f1');s.onchange=()=>$('#cs').textContent=byId(s.value).stock+' units';s.onchange()})}
function suggest(p){return Math.max(p.dailySales*5,p.reorderLevel*2-p.stock,1)}
function mReorder(id){const p=byId(id);modal('Reorder Product',`<div class="info"><div><span>Product</span><b>${p.name}</b></div><div><span>Current Stock</span><b>${p.stock}</b></div><div><span>Reorder Level</span><b>${p.reorderLevel}</b></div><div><span>Average Daily Sales</span><b>${p.dailySales}/day</b></div><div><span>Supplier</span><b>${p.supplier}</b></div></div>${fld('Suggested Quantity (units)','f1','number','required min="1" value="'+suggest(p)+'"')}`,'Create Reorder',g=>{S.reorders.unshift({id:Date.now(),product:p.name,supplier:p.supplier,quantity:+g('f1'),status:'Pending',date:TODAY});log('reorder',`${p.name} × ${g('f1')}`);renderAll();toast('Reorder request created')})}
function mView(id){const p=byId(id);modal(p.name,`<div class="info"><div><span>SKU</span><b>${p.sku}</b></div><div><span>Category</span><b>${p.category}</b></div><div><span>Current Stock</span><b>${p.stock}</b></div><div><span>Reorder Level</span><b>${p.reorderLevel}</b></div><div><span>Supplier</span><b>${p.supplier}</b></div><div><span>Purchase / Selling</span><b>${inr(p.purchasePrice)} / ${inr(p.sellingPrice)}</b></div><div><span>Status</span><span class="b ${stat(p)}">${LBL[stat(p)]}</span></div></div>`,null)}
/* ===== multi-page layer ===== */
const page=document.body.dataset.page,SET=SETV,doc=id=>document.getElementById(id);
const put=(id,h)=>{const e=doc(id);if(e)e.innerHTML=h},$v=id=>{const e=doc(id);return e?e.value:''};
const em=(t,s='')=>`<div class="empty"><b>${t}</b>${s}</div>`,none=(n,t,s)=>`<tr><td colspan="${n}">${em(t,s)}</td></tr>`,esc=s=>String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
const fd=d=>{const f=SET().df,o=new Date(d+'T00:00');return f==='iso'?d:f==='us'?o.toLocaleDateString('en-US'):o.toLocaleDateString('en-GB',{day:'numeric',month:'short'})};
P.sun='<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>';P.moon='<path d="M21 13A9 9 0 1111 3a7 7 0 0010 10z"/>';
const PG=[['dashboard','Dashboard','dash'],['products','Products','box'],['sales','Sales','cart'],['purchases','Purchases','truck'],['alerts','Alerts','bell'],['reports','Reports','chart'],['suppliers','Suppliers','users'],['stock-history','Stock History','hist'],['reorder-requests','Reorder Requests','ref'],['ai-insights','AI Insights','spark'],['settings','Settings','gear'],['help','Help &amp; Support','help']];
const kp=(id,a)=>put(id,a.map(x=>`<div class="card kpi"><div class="top"><span>${x[0]}</span><span class="ico ${x[4]||''}">${ic(x[3])}</span></div><div class="n">${x[1]}</div><div class="sub">${x[2]}</div></div>`).join(''));
const hbars=l=>{const m=Math.max(...l.map(x=>x[1]),1);return l.map(([n,v,t])=>`<div><div class="r"><span>${n}</span><b>${t||v}</b></div><div class="trk"><i style="width:${v/m*100}%"></i></div></div>`).join('')};
function gbar(id,A,B,L){const W=640,H=220,pl=34,pb=24,pt=10,mx=Math.ceil(Math.max(...A,...B)/20)*20,bw=(W-pl-8)/A.length,Y=v=>pt+(H-pt-pb)*(1-v/mx);let g='';for(let i=0;i<=3;i++){const y=pt+(H-pt-pb)*i/3;g+=`<line x1="${pl}" x2="${W-8}" y1="${y}" y2="${y}" class="gl"/><text x="${pl-6}" y="${y+4}" text-anchor="end" class="ax">${Math.round(mx*(1-i/3))}</text>`}
put(id,`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Stock in versus stock out">${g}${A.map((a,i)=>{const x=pl+bw*i+bw*.12,w=bw*.34;return`<rect class="bar" x="${x}" y="${Y(a)}" width="${w}" height="${H-pb-Y(a)}" rx="3" style="fill:rgba(92,203,138,.65)"/><rect class="bar" x="${x+w+2}" y="${Y(B[i])}" width="${w}" height="${H-pb-Y(B[i])}" rx="3" style="fill:rgba(227,176,75,.65)"/><text x="${pl+bw*i+bw/2}" y="${H-6}" text-anchor="middle" class="ax">${L[i]}</text>`}).join('')}</svg><p class="note">Green: stock in · Amber: stock out (demo series)</p>`)}
function lsvg(id,V,L,u=''){const W=640,H=200,pl=38,pb=24,pt=12,mn=Math.min(...V)*.9,mx=Math.max(...V)*1.08,X=i=>pl+(W-pl-10)*i/(V.length-1),Y=v=>pt+(H-pt-pb)*(1-(v-mn)/(mx-mn)),st=Math.ceil(V.length/7);let g='';for(let i=0;i<=3;i++){const y=pt+(H-pt-pb)*i/3;g+=`<line x1="${pl}" x2="${W-10}" y1="${y}" y2="${y}" class="gl"/><text x="${pl-6}" y="${y+4}" text-anchor="end" class="ax">${(mx-(mx-mn)*i/3).toFixed(u?0:0)}${u}</text>`}
const d='M'+V.map((v,i)=>X(i)+','+Y(v)).join('L');put(id,`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Trend chart">${g}<path d="${d}L${X(V.length-1)},${H-pb}L${X(0)},${H-pb}Z" fill="rgba(95,208,200,.1)"/><path class="ln" pathLength="1" d="${d}"/>${V.map((v,i)=>`<circle cx="${X(i)}" cy="${Y(v)}" r="3" fill="var(--card)" stroke="var(--cy)" stroke-width="2"><title>${L[i]}: ${v}${u}</title></circle>${i%st==0?`<text x="${X(i)}" y="${H-6}" text-anchor="middle" class="ax">${L[i]}</text>`:''}`).join('')}</svg>`)}
function setRQ(id,st){const r=S.reorders.find(x=>x.id==id),p=S.products.find(x=>x.name===r.product);if(st==='Received'&&r.status!=='Received'&&p){hint='Stock Received';p.stock+=r.quantity;S.mv.in+=r.quantity;log('purchase',`${p.name} × ${r.quantity} received`)}r.status=st;renderAll();toast(st==='Received'?'Stock updated successfully':'Reorder marked as '+st)}
function mEdit(id){const p=byId(id);modal('Edit Product',`<div class="fr">${fld('Product Name','f1','text','required value="'+esc(p.name)+'"','w')}${fld('SKU','f2','text','required value="'+esc(p.sku)+'"')}${sel('Category','f3',CATS)}${fld('Stock','f4','number','required min="0" value="'+p.stock+'"')}${fld('Reorder Level','f5','number','required min="0" value="'+p.reorderLevel+'"')}${fld('Supplier','f6','text','required value="'+esc(p.supplier)+'"','w')}${fld('Purchase Price (₹)','f7','number','required min="0" step="0.01" value="'+p.purchasePrice+'"')}${fld('Selling Price (₹)','f8','number','required min="0" step="0.01" value="'+p.sellingPrice+'"')}</div>`,'Save Changes',g=>{const pv=stat(p),o=p.stock;Object.assign(p,{name:g('f1').trim(),sku:g('f2').trim(),category:g('f3'),stock:+g('f4'),reorderLevel:+g('f5'),supplier:g('f6').trim(),purchasePrice:+g('f7'),sellingPrice:+g('f8')});if(p.stock!==o)log('adjust',`${p.name}: ${o} → ${p.stock} (edited)`);changed(p,pv);renderAll();toast('Product updated successfully')},()=>{$('#f3').value=p.category})}
function mDel(id){const p=byId(id);modal('Delete Product',`<p class="sub" style="margin-bottom:14px">Delete <b>${esc(p.name)}</b> from inventory? This can’t be undone.</p>`,'Delete Product',()=>{S.products=S.products.filter(x=>x.id!=id);delete S.snap[id];renderAll();toast('Product deleted')})}
function mPick(){modal('Create Order',sel('Product','f1',popt(),'w'),'Continue',g=>{const i=g('f1');setTimeout(()=>mReorder(i),250)})}
function mSup(id){const s=id?S.suppliers.find(x=>x.id==id):null;modal(s?'Edit Supplier':'Add Supplier',`<div class="fr">${fld('Supplier Name','f1','text','required value="'+esc(s?s.name:'')+'"','w')}${sel('Category','f2',CATS)}${sel('Status','f5','<option>Active</option><option>Inactive</option>')}${fld('Products Supplied','f3','number','required min="0" value="'+(s?s.products:0)+'"')}${fld('Open Orders','f4','number','required min="0" value="'+(s?s.orders:0)+'"')}${fld('Contact (email)','f6','email','required value="'+esc(s?s.contact:'')+'"','w')}</div>`,s?'Save Changes':'Add Supplier',g=>{const o={name:g('f1').trim(),category:g('f2'),products:+g('f3'),orders:+g('f4'),status:g('f5'),contact:g('f6').trim()};if(s)Object.assign(s,o);else S.suppliers.push({id:Date.now(),...o});renderAll();toast(s?'Supplier updated successfully':'Supplier added successfully')},()=>{if(s){$('#f2').value=s.category;$('#f5').value=s.status}})}
const sup=id=>S.suppliers.find(x=>x.id==id);
function mSupView(id){const s=sup(id);modal(s.name,`<div class="info"><div><span>Category</span><b>${s.category}</b></div><div><span>Products supplied</span><b>${s.products}</b></div><div><span>Open orders</span><b>${s.orders}</b></div><div><span>Status</span><b>${s.status}</b></div><div><span>Contact</span><b>${esc(s.contact)}</b></div></div>`,null)}
function mContact(id){const s=sup(id);modal('Contact '+s.name,`<p class="sub" style="margin-bottom:12px">Demo contact address for this supplier:</p><p><a class="link" href="mailto:${esc(s.contact)}">${esc(s.contact)}</a></p>`,null)}
const RD={
products(){const c=cnt();kp('pk',[['Total Products',c.T,'Across your catalogue','box','c-c'],['Healthy',c.H,'Above reorder level','boxes','c-g'],['Low Stock',c.L,'At or below reorder level','warn','c-a'],['Out of Stock',c.O,'Zero units available','alert','c-r']]);
const q=query.trim().toLowerCase(),cat=$v('pc'),stt=$v('pf'),l=S.products.filter(p=>(!q||[p.name,p.sku,p.category,p.supplier].some(x=>x.toLowerCase().includes(q)))&&(!cat||p.category===cat)&&(!stt||stat(p)===stt));
put('pt',l.map(p=>`<tr><td><b>${p.name}</b></td><td>${p.sku}</td><td>${p.category}</td><td><b>${p.stock}</b></td><td>${p.reorderLevel}</td><td>${p.supplier}</td><td><span class="b ${stat(p)}">${LBL[stat(p)]}</span></td><td class="nw"><button class="btn" data-v="${p.id}">View</button> <button class="btn" data-e="${p.id}">Edit</button> <button class="btn" data-d="${p.id}">Delete</button></td></tr>`).join(''));
put('pte',l.length?'':S.products.length?em('No products found','Adjust your search or filters.'):em('No products yet','Add your first product to start tracking inventory.')+'<div class="empty"><button class="btn p" data-act="add">Add Product</button></div>')},
sales(){const T=S.sales.filter(s=>!s.seed&&s.date===TODAY),a=9840+T.reduce((x,s)=>x+s.quantity*s.price,0),tx=32+T.length;kp('sk',[["Today’s Sales",inr(a),'Revenue so far today','cart','c-g'],['Transactions',tx,'Bills recorded today','chart','c-c'],['Units Sold',148+T.reduce((x,s)=>x+s.quantity,0),'Items sold today','boxes','c-c'],['Average Sale',inr(a/tx),'Per transaction','box','c-a']]);
put('ss',S.sales.slice(0,14).map(s=>`<tr><td>${fd(s.date)}</td><td><b>${s.product}</b></td><td>${s.quantity}</td><td>${inr(s.price)}</td><td>${inr(s.quantity*s.price)}</td><td><span class="b ok">Completed</span></td></tr>`).join('')||none(6,'No sales yet','Record your first sale to see it here.'))},
purchases(){const T=S.purchases.filter(s=>!s.seed&&s.date===TODAY);kp('uk',[["Today’s Purchases",inr(18450+T.reduce((x,s)=>x+s.quantity*s.price,0)),'Value received today','truck','c-c'],['Units Received',246+T.reduce((x,s)=>x+s.quantity,0),'Items received today','boxes','c-g'],['Suppliers',S.suppliers.length+9,'In your network','users','c-c'],['Pending Orders',S.reorders.filter(r=>r.status!=='Received').length+2,'Awaiting delivery','ref','c-a']]);
put('pu',S.purchases.slice(0,14).map(s=>`<tr><td>${fd(s.date)}</td><td><b>${s.product}</b></td><td>${s.supplier}</td><td>${s.quantity}</td><td>${inr(s.price)}</td><td>${inr(s.quantity*s.price)}</td><td><span class="b ok">Received</span></td></tr>`).join('')||none(7,'No purchases yet','Record incoming stock to see it here.'));
const m={};S.purchases.forEach(s=>m[s.supplier]=(m[s.supplier]||0)+s.quantity*s.price);put('psp',hbars(Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([n,v])=>[n,v,inr(v)]))||em('No spend yet'))},
alerts(){const c=cnt(),lo=S.products.filter(p=>stat(p)==='low'),ou=S.products.filter(p=>stat(p)==='out');kp('ak',[['Low Stock',c.L,'At or below reorder level','warn','c-a'],['Out of Stock',c.O,'Products unavailable','alert','c-r'],['Reorder Recommended',Math.max(0,8-(S.reorders.length-4)),'Suggested for replenishment','ref','c-c']]);
const btn=p=>`<button class="btn" data-v="${p.id}">View Product</button> <button class="btn" data-o="${p.id}" ${open(p)?'disabled':''}>${open(p)?'Requested':'Create Reorder'}</button>`,row=p=>`<tr><td><b>${p.name}</b><small>${p.category}</small></td><td>${p.stock} / ${p.reorderLevel}</td><td><span class="b ${stat(p)}">${LBL[stat(p)]}</span></td><td class="nw">${btn(p)}</td></tr>`;
put('al',lo.map(row).join('')||none(4,'No low-stock alerts'));put('ao',ou.map(row).join('')||none(4,'No out-of-stock alerts'));put('aln',`+${S.extra.low} more low-stock and ${S.extra.out} out-of-stock items in the wider demo catalogue.`);
put('ar',[...ou,...lo].map(p=>`<tr><td><b>${p.name}</b></td><td>${p.stock} / ${p.reorderLevel}</td><td>${p.dailySales}/day</td><td>${p.stock?'~'+Math.max(1,Math.round(p.stock/Math.max(p.dailySales,1)))+' days':'Now'}</td><td>${suggest(p)} units</td><td>${p.supplier}</td><td class="nw">${btn(p)}</td></tr>`).join('')||none(7,'Nothing to reorder','All products are above their reorder levels.'))},
reports(){const n=range==7?7:range==30?10:13,L=Array.from({length:n},(_,i)=>range==7?DN[i]:range==30?'D'+(i*3+1):'Wk'+(i+1)),A=L.map((_,i)=>Math.round(60+Math.sin(i*1.4)*18+i*2)),B=L.map((_,i)=>Math.round(55+Math.cos(i*1.1)*16+i));A[n-1]+=S.mv.in-410;B[n-1]+=S.mv.out-372;gbar('mvc',A,B,L);
const c=cnt();lsvg('lst',[9,10,10,11,12,11,c.L],['Sep 24','Sep 25','Sep 26','Sep 27','Sep 28','Sep 29','Today'])},
suppliers(){const a=S.suppliers.filter(s=>s.status==='Active').length;kp('vk',[['Total Suppliers',S.suppliers.length+9,'In your network','users','c-c'],['Active Suppliers',a+7,'Supplying now','truck','c-g'],['Pending Orders',S.reorders.filter(r=>r.status!=='Received').length+2,'Awaiting delivery','ref','c-a']]);
put('vt',S.suppliers.map(s=>`<tr><td><b>${s.name}</b></td><td>${s.category}</td><td>${s.products}</td><td>${s.orders}</td><td><span class="b ${s.status==='Active'?'ok':'low'}">${s.status}</span></td><td>${esc(s.contact)}</td><td class="nw"><button class="btn" data-sv="${s.id}">View</button> <button class="btn" data-se="${s.id}">Edit</button> <button class="btn" data-sc="${s.id}">Contact</button></td></tr>`).join('')||none(7,'No suppliers yet','Add a supplier to track replenishment sources.'))},
'stock-history'(){const pv=$v('hp'),ty=$v('ht'),dt=$v('hd'),l=S.hist.filter(x=>(!pv||x.p===pv)&&(!ty||x.t===ty)&&(!dt||x.d===dt)),i=l.filter(x=>x.q>0).reduce((a,x)=>a+x.q,0),o=l.filter(x=>x.q<0).reduce((a,x)=>a-x.q,0);
kp('hk',[['Movements',l.length,'Matching current filters','hist','c-c'],['Stock In','+'+i,'Units added','truck','c-g'],['Stock Out','−'+o,'Units removed','cart','c-a'],['Net Movement',(i-o>=0?'+':'')+(i-o),'In minus out','chart']]);
put('htb',l.map(x=>`<tr><td>${fd(x.d)}</td><td><b>${x.p}</b></td><td>${x.t}</td><td class="${x.q>0?'c-g':'c-a'}"><b>${x.q>0?'+':''}${x.q}</b></td><td>${x.prev}</td><td>${x.now}</td><td>${x.ref}</td></tr>`).join('')||none(7,'No movements found','Try clearing the filters.'))},
'reorder-requests'(){const n=k=>S.reorders.filter(r=>r.status===k).length+S.extra.rq[k];kp('rk',[['Pending',n('Pending'),'Waiting to be ordered','ref','c-a'],['Ordered',n('Ordered'),'On the way from suppliers','truck','c-c'],['Received',n('Received'),'Added to stock','boxes','c-g']]);
put('rt',S.reorders.map(r=>{const p=S.products.find(x=>x.name===r.product),a=r.status==='Pending'?`<button class="btn" data-rs="${r.id}:Ordered">Mark Ordered</button>`:r.status==='Ordered'?`<button class="btn" data-rs="${r.id}:Received">Mark Received</button>`:'<span class="sub">Completed</span>';return`<tr><td><b>${r.product}</b></td><td>${r.supplier}</td><td>${p?p.stock:'—'}</td><td>${r.quantity} units</td><td><span class="b ${r.status==='Received'?'ok':r.status==='Ordered'?'rq':'low'}">${r.status}</span></td><td>${fd(r.date)}</td><td class="nw">${a}</td></tr>`}).join('')||none(7,'No reorder requests','Create an order for a low-stock product.'))},
'ai-insights'(){const P=S.products,f=P.find(p=>p.name==='Coca-Cola 750ml')||[...P].sort((a,b)=>b.dailySales-a.dailySales)[0],s=P.find(p=>p.name==='Tata Salt 1kg')||[...P].filter(p=>p.stock>0).sort((a,b)=>a.dailySales-b.dailySales)[0],o=P.find(p=>p.stock===0),tg='<span class="tag">Demo AI Insight</span>';
const ins=(id,t,p,tx,x)=>put(id,`<div class="ch"><div><h3>${t}</h3></div>${tg}</div>`+(p?`<h4 style="font-size:17px;margin-bottom:10px">${p.name}</h4><p class="sub" style="margin-bottom:12px">${tx}</p>${x}`:em('Not enough data','Add products to generate this insight.')));
const mini=p=>`<div class="mini"><div><span>Stock</span><b>${p.stock}</b></div><div><span>Daily Sales</span><b>${p.dailySales}/day</b></div><div><span>Cover</span><b>${p.dailySales?'~'+Math.round(p.stock/p.dailySales)+' days':'—'}</b></div></div>`;
ins('ai2','Fast Moving Product',f,'Recent sales indicate strong movement.',f?mini(f):'');ins('ai3','Slow Moving Product',s,'Lower recent sales compared with other tracked products.',s?mini(s):'');
ins('ai4','Reorder Suggestion',o,'Out of stock. Suggested action: create a reorder request.',o?`<div class="mini"><div><span>Current Stock</span><b>0</b></div><div><span>Suggested Qty</span><b>${suggest(o)}</b></div><div><span>Supplier</span><b style="font-size:12px">${o.supplier}</b></div></div><button class="btn p" data-o="${o.id}" ${open(o)?'disabled':''}>${open(o)?'Reorder Requested':'Create Reorder'}</button>`:'');
const d=series();lsvg('ac1',d.map(x=>x.v/1000),d.map(x=>x.l),'k');
put('ac2',`<div class="hb">${hbars([...P].sort((a,b)=>b.dailySales-a.dailySales).slice(0,6).map(p=>[p.name,p.dailySales,p.dailySales+'/day']))}</div>`);
put('ac3',`<div class="hb">${hbars(P.filter(p=>p.stock>0&&p.dailySales>0).map(p=>[p,p.stock/p.dailySales]).sort((a,b)=>a[1]-b[1]).slice(0,6).map(([p,dd])=>[p.name,Math.max(.4,14-dd),'~'+Math.round(dd)+' days left']))}</div>`);
put('ac4',`<div class="tw"><table style="min-width:340px"><tbody>${P.filter(p=>stat(p)!=='ok').map(p=>`<tr><td><b>${p.name}</b><small>${p.supplier}</small></td><td>${suggest(p)} units</td><td><button class="btn" data-o="${p.id}" ${open(p)?'disabled':''}>${open(p)?'Requested':'Reorder'}</button></td></tr>`).join('')||none(3,'No suggestions','Stock looks healthy.')}</tbody></table></div>`)}};
function renderAll(){renderBase();const f=RD[page];f&&f();const n=bell().length;$('#badge').textContent=n;$('#badge').style.display=n?'grid':'none';save()}
function bell(){const c=cnt(),st=SET(),pd=S.reorders.filter(r=>r.status==='Pending').length+S.extra.rq.Pending;return[[st.pn!==false&&st.n1!==false?c.L:0,`${c.L} products are low on stock.`,'alerts.html','warn','c-a'],[st.n2!==false?c.O:0,`${c.O} products are out of stock.`,'alerts.html','alert','c-r'],[st.n3!==false?pd:0,`${pd} reorder requests are pending.`,'reorder-requests.html','ref','c-c']].filter(x=>x[0]>0)}
let setTh=function(t){document.documentElement.dataset.theme=t;try{localStorage.setItem('restock-theme',t)}catch(e){}const b=doc('theme');if(b){b.innerHTML=ic(t==='dark'?'sun':'moon');b.title=t==='dark'?'Switch to light theme':'Switch to dark theme'}const a=doc('r-'+t);if(a)a.checked=true;const w=doc('sw-theme');if(w)w.checked=t==='light'}
/* shell */
const st0=SET(),sn=st0.name||'Yash Retail Store',bd=document.body.dataset,grp=(h,a)=>`<h6>${h}</h6>`+a.map(([f,l,i])=>`<a href="${f}.html" class="${f===page?'on':''}" ${f===page?'aria-current="page"':''}>${ic(i)}${l}</a>`).join('');
doc('side').innerHTML=`<div class="logo"><b>${ic('box')}</b>ReStock</div><nav>${grp('Main',PG.slice(0,6))}${grp('Management',PG.slice(6,9))}${grp('Insights',PG.slice(9,10))}${grp('Account',PG.slice(10))}</nav><div class="store"><div class="av">${esc(sn[0])}</div><div><b>${esc(sn)}</b><small>${esc(st0.type||'Small Retail')}</small></div></div>`;
doc('hdr').innerHTML=`<div style="display:flex;gap:12px;align-items:flex-start"><button class="pill menu" id="ham" aria-label="Open menu">${ic('menu')}</button><div><h1>${bd.title}</h1><p class="sub">${bd.sub}</p></div></div><div class="tools"><label class="pill search">${ic('search')}<input id="q" type="search" placeholder="Search products…" aria-label="Search products"></label><button class="pill bell" id="bell" aria-label="Notifications" aria-haspopup="true">${ic('bell')}<em id="badge">3</em></button><button class="pill tg" id="theme" aria-label="Toggle theme"></button><button class="pill hide-s" id="storeb">${esc(sn)}${ic('chev')}</button><div class="user"><div class="av">Y</div><div><b>Yash</b><small>Store Admin</small></div></div><div class="dd" id="dd"></div></div>`;
setTh(document.documentElement.dataset.theme||'dark');
put('qa',[['plus','Add Product','add'],['cart','Record Sale','sale'],['truck','Record Purchase','pur'],['adj','Stock Adjustment','adj']].map(a=>`<div class="card" style="padding:0"><button data-act="${a[2]}"><span class="ico">${ic(a[0])}</span>${a[1]}</button></div>`).join(''));
if(page==='stock-history')put('hp','<option value="">All products</option>'+[...new Set(S.products.map(p=>p.name).concat(S.hist.map(h=>h.p)))].map(n=>`<option>${n}</option>`).join(''));
/* wiring */
const shut=()=>{doc('side').classList.remove('open');doc('veil').classList.remove('open')};
document.addEventListener('click',e=>{const t=e.target.closest('[data-act],[data-v],[data-o],[data-e],[data-d],[data-sv],[data-se],[data-sc],[data-rs]');if(!e.target.closest('#dd,#bell'))doc('dd').classList.remove('open');if(!t)return;const d=t.dataset;
if(d.act)({add:mAdd,sale:()=>mSale(),pur:()=>mPur(),adj:mAdj,sup:()=>mSup(),pick:mPick})[d.act]();if(d.v)mView(d.v);if(d.o)mReorder(d.o);if(d.e)mEdit(d.e);if(d.d)mDel(d.d);if(d.sv)mSupView(d.sv);if(d.se)mSup(d.se);if(d.sc)mContact(d.sc);if(d.rs){const[i,s]=d.rs.split(':');setRQ(i,s)}});
doc('theme').onclick=()=>setTh(document.documentElement.dataset.theme==='dark'?'light':'dark');
doc('ham').onclick=()=>{doc('side').classList.add('open');doc('veil').classList.add('open')};doc('veil').onclick=shut;
doc('storeb').onclick=()=>toast('Only one store is connected in this demo');
doc('bell').onclick=()=>{const it=bell();doc('dd').innerHTML='<h4>Notifications</h4>'+(it.length?it.map(x=>`<a href="${x[2]}" style="text-decoration:none;color:inherit"><button style="width:100%"><span class="${x[4]}">${ic(x[3])}</span>${x[1]}</button></a>`).join(''):em('No alerts','You’re all caught up.'));doc('dd').classList.toggle('open')};
doc('q').oninput=e=>{query=e.target.value;const s=doc('ps');if(s)s.value=query;if(page==='dashboard')renderTable();if(page==='products')RD.products()};
doc('q').onkeydown=e=>{if(e.key==='Enter'&&page!=='products'&&page!=='dashboard')location.href='products.html?q='+encodeURIComponent(e.target.value)};
const ps=doc('ps');if(ps)ps.oninput=e=>{query=e.target.value;doc('q').value=query;RD.products()};
const qp=new URLSearchParams(location.search).get('q');if(qp){query=qp;doc('q').value=qp;if(ps)ps.value=qp}
['pc','pf','hp','ht','hd'].forEach(i=>{const e=doc(i);if(e)e.onchange=()=>RD[page]()});
const sg=doc('seg');if(sg)sg.onclick=e=>{const b=e.target.closest('button');if(!b)return;range=+b.dataset.r;sg.querySelector('.on').classList.remove('on');b.classList.add('on');renderChart();if(page==='reports')RD.reports()};
const al=doc('allal');if(al)al.onclick=()=>{query='';doc('q').value='';renderTable()};
if(page==='settings'){const s=SET(),F=[['sname','name'],['stype','type'],['semail','email'],['scur','cur'],['sdf','df']],T=['pn','n1','n2','n3'];F.forEach(([i,k])=>{if(s[k]!==undefined)doc(i).value=s[k]});T.forEach(k=>doc(k).checked=s[k]!==false);
['dark','light'].forEach(t=>doc('r-'+t).onchange=()=>setTh(t));doc('sw-theme').onchange=e=>setTh(e.target.checked?'light':'dark');
doc('save').onclick=()=>{if(!doc('semail').checkValidity()){doc('semail').reportValidity();return}const o={};F.forEach(([i,k])=>o[k]=doc(i).value);T.forEach(k=>o[k]=doc(k).checked);try{localStorage.setItem('restock-settings',JSON.stringify(o))}catch(e){}toast('Settings saved');setTimeout(()=>location.reload(),800)}}
renderAll();setTimeout(()=>{doc('main').classList.remove('loading');if(doc('cw'))renderChart();renderTop()},600);setInterval(renderAct,60000);
/* ===== motion + remaining buttons ===== */
document.addEventListener('pointerdown',e=>{const b=e.target.closest('.btn,.ib,.seg button,.qa button,nav a');if(!b||b.disabled)return;const r=b.getBoundingClientRect(),s=Math.max(r.width,r.height)*2,x=document.createElement('span');x.className='rp';x.style.cssText=`width:${s}px;height:${s}px;left:${e.clientX-r.left-s/2}px;top:${e.clientY-r.top-s/2}px`;b.append(x);setTimeout(()=>x.remove(),600)});
document.addEventListener('click',e=>{const a=e.target.closest('a[href$=".html"]');if(!a||e.ctrlKey||e.metaKey||a.target)return;e.preventDefault();const h=a.getAttribute('href');if(h===location.pathname.split('/').pop())return;doc('main').classList.add('leaving');setTimeout(()=>location.href=h,180)});
const _st=setTh;setTh=function(t){document.documentElement.classList.add('tx');_st(t);setTimeout(()=>document.documentElement.classList.remove('tx'),450)};
function menu(k,h,stop){const d=doc('dd'),same=d.classList.contains('open')&&d.dataset.k===k;d.dataset.k=k;d.innerHTML=h;d.classList.toggle('open',!same)}
const bellH=()=>{const it=bell();return'<h4>Notifications</h4>'+(it.length?it.map(x=>`<button data-m="go|${x[2]}"><span class="${x[4]}">${ic(x[3])}</span>${x[1]}</button>`).join(''):em('No alerts','You’re all caught up.'))};
doc('bell').onclick=e=>{e.stopPropagation();menu('bell',bellH())};
doc('storeb').onclick=e=>{e.stopPropagation();menu('store','<h4>Switch store</h4>'+['Yash Retail Store','Yash Mini Market','Yash Pharmacy'].map(n=>`<button data-m="store|${n}"><span class="c-c">${ic('box')}</span>${n}${n===sn?'<span class="c-g" style="margin-left:auto">✓</span>':''}</button>`).join(''))};
const usr=document.querySelector('.user');usr.tabIndex=0;usr.setAttribute('role','button');usr.setAttribute('aria-label','Account menu');
usr.onclick=e=>{e.stopPropagation();menu('user',`<h4>Yash · Store Admin</h4><button data-m="go|settings.html"><span class="c-c">${ic('gear')}</span>Settings</button><button data-m="go|help.html"><span class="c-c">${ic('help')}</span>Help &amp; Support</button><button data-m="theme|"><span class="c-c">${ic('sun')}</span>Toggle theme</button><div class="sep"></div><button data-m="reset|"><span class="c-r">${ic('ref')}</span>Reset demo data</button>`)};
usr.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();usr.click()}};
doc('dd').onclick=e=>{const b=e.target.closest('[data-m]');if(!b)return;const[a,v]=b.dataset.m.split('|');doc('dd').classList.remove('open');
if(a==='go'){doc('main').classList.add('leaving');setTimeout(()=>location.href=v,180)}
if(a==='theme')setTh(document.documentElement.dataset.theme==='dark'?'light':'dark');
if(a==='store'){const s=SET();s.name=v;try{localStorage.setItem('restock-settings',JSON.stringify(s))}catch(x){}toast('Switched to '+v);setTimeout(()=>location.reload(),700)}
if(a==='reset')modal('Reset Demo Data','<p class="sub" style="margin-bottom:14px">Restore all products, sales and history to the original demo state?</p>','Reset',()=>{S=seed();S.snap=null;renderAll();toast('Demo data reset')})};
document.querySelector('.store').onclick=()=>{doc('main').classList.add('leaving');setTimeout(()=>location.href='settings.html',180)};
document.querySelector('.logo').onclick=()=>{location.href='dashboard.html'};
document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName)){e.preventDefault();doc('q').focus()}});
(function cu(){setTimeout(()=>document.querySelectorAll('.kpi .n').forEach(n=>{const m=n.textContent.match(/[\d,]+/);if(!m)return;const t=+m[0].replace(/,/g,''),pre=n.textContent.slice(0,m.index),suf=n.textContent.slice(m.index+m[0].length),t0=performance.now();const f=x=>{const p=Math.min(1,(x-t0)/700),v=Math.round(t*(1-Math.pow(1-p,3)));n.textContent=pre+v.toLocaleString('en-IN')+suf;if(p<1)requestAnimationFrame(f)};requestAnimationFrame(f)}),650)})();
